### ISSUE TITLE
rate limit

### ISSUE THREAD

**Issue by techguydave** [synth3tk/node-prettylights#3]
For Twitch-imposed reasons, as well as performance, the amount of times the bot responds should be no more than _x-amount_ per _amount_. Gotta look up what the limits are, then play it even safer than that for good measures.

In the future, if the Ankhbot rewrite allows access to the VIP list, then I'll probably have some sort of priority system where VIPs can use it more often than regular viewers, although as a whole the commands will still be limited.

Example: Individual VIPs can change the light every minute, regulars every two minutes, but the lights are globally limited to 5 minutes.

**Comment by SGrondin** [comment]
[This module](https://github.com/SGrondin/bottleneck) I made might come in handy to do just that, I hope you find it helpful.

**Comment by techguydave** [comment]
Awesome! Looks like it's perfect for what I'm trying to do. I'll give it a shot.

**Comment by SGrondin** [comment]
Since you have both a global limit and a per-user one, you'll need to make a global limiter and one limiter per user (obviously you can do it on the fly). Then chain them together like this `user1Limiter.chain(globalLimiter)`. If all the user limiters have the same rate limits and the users come and go all the time, then you should use the Cluster to create your user limiters because it'll manage it all for you. Lemme know if you have any questions :)
